name: Contribution snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths: [.github/workflows/snake.yml]

permissions:
  contents: write

concurrency:
  group: snake
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-light.svg?palette=github-light&color_snake=#f0468a&color_dots=#ebedf0,#a5f3fc,#22d3ee,#0891b2,#155e75
            dist/snake-dark.svg?palette=github-dark&color_snake=#f0468a&color_dots=#161b22,#0e4451,#0e7490,#06b6d4,#67e8f9

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update contribution snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
